OpenAI_key=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"
import streamlit as st

key = st.secrets["OpenAI_key"]
